export type GeometricLinzklarId =
  | "一"
  | "七"
  | "三"
  | "上"
  | "下"
  | "与"
  | "中"
  | "之"
  | "乎"
  | "九"
  | "二"
  | "互"
  | "五"
  | "亦"
  | "享"
  | "人"
  | "从"
  | "付"
  | "件"
  | "位"
  | "低"
  | "体"
  | "何"
  | "佰"
  | "使"
  | "俐"
  | "倉"
  | "倒"
  | "値"
  | "健"
  | "傷"
  | "傾"
  | "僚"
  | "兄"
  | "光"
  | "党"
  | "入"
  | "全"
  | "八"
  | "六"
  | "兵"
  | "其"
  | "内"
  | "再"
  | "冠"
  | "冬"
  | "処"
  | "凹"
  | "函"
  | "刀"
  | "別"
  | "刺"
  | "刻"
  | "前"
  | "力"
  | "加"
  | "助"
  | "労"
  | "勿"
  | "包"
  | "北"
  | "十"
  | "南"
  | "即"
  | "卵"
  | "友"
  | "反"
  | "受"
  | "叛"
  | "口"
  | "古"
  | "叫"
  | "可"
  | "右"
  | "吁"
  | "同"
  | "名"
  | "后"
  | "吏"
  | "㕮"
  | "周"
  | "味"
  | "呻"
  | "咍"
  | "哇"
  | "哩"
  | "唯"
  | "啌"
  | "善"
  | "嗅"
  | "噫"
  | "囁"
  | "四"
  | "囲"
  | "国"
  | "圧"
  | "在"
  | "地"
  | "型"
  | "増"
  | "壁"
  | "壊"
  | "声"
  | "夏"
  | "外"
  | "夘"
  | "多"
  | "大"
  | "天"
  | "失"
  | "奮"
  | "女"
  | "如"
  | "始"
  | "子"
  | "字"
  | "季"
  | "学"
  | "守"
  | "官"
  | "定"
  | "宦"
  | "家"
  | "寐"
  | "寒"
  | "寝"
  | "将"
  | "小"
  | "少"
  | "属"
  | "層"
  | "山"
  | "岩"
  | "島"
  | "川"
  | "左"
  | "巫"
  | "己"
  | "巻"
  | "布"
  | "帝"
  | "席"
  | "常"
  | "帽"
  | "平"
  | "広"
  | "店"
  | "座"
  | "弓"
  | "形"
  | "彼"
  | "律"
  | "後"
  | "従"
  | "御"
  | "心"
  | "必"
  | "怖"
  | "思"
  | "急"
  | "恒"
  | "悪"
  | "意"
  | "我"
  | "或"
  | "戦"
  | "手"
  | "抗"
  | "振"
  | "挽"
  | "撃"
  | "故"
  | "救"
  | "散"
  | "文"
  | "斧"
  | "新"
  | "於"
  | "族"
  | "日"
  | "星"
  | "春"
  | "時"
  | "普"
  | "書"
  | "月"
  | "木"
  | "机"
  | "村"
  | "来"
  | "杯"
  | "東"
  | "果"
  | "柔"
  | "株"
  | "械"
  | "棉"
  | "棚"
  | "極"
  | "榎"
  | "槍"
  | "横"
  | "樽"
  | "橋"
  | "機"
  | "欽"
  | "歌"
  | "止"
  | "正"
  | "此"
  | "歪"
  | "母"
  | "毎"
  | "毛"
  | "氏"
  | "民"
  | "水"
  | "汝"
  | "汪"
  | "決"
  | "油"
  | "浬"
  | "海"
  | "淮"
  | "深"
  | "混"
  | "清"
  | "満"
  | "激"
  | "火"
  | "為"
  | "無"
  | "煙"
  | "父"
  | "片"
  | "牌"
  | "牛"
  | "牡"
  | "物"
  | "犬"
  | "猫"
  | "獣"
  | "王"
  | "球"
  | "琴"
  | "瑪"
  | "甘"
  | "生"
  | "産"
  | "男"
  | "疲"
  | "白"
  | "百"
  | "皇"
  | "皷"
  | "目"
  | "直"
  | "真"
  | "短"
  | "石"
  | "硫"
  | "硬"
  | "祖"
  | "神"
  | "祭"
  | "禦"
  | "秋"
  | "科"
  | "種"
  | "積"
  | "穏"
  | "穐"
  | "穴"
  | "立"
  | "端"
  | "竹"
  | "竺"
  | "笑"
  | "笙"
  | "笛"
  | "筆"
  | "等"
  | "筒"
  | "箏"
  | "箱"
  | "米"
  | "糸"
  | "紙"
  | "素"
  | "累"
  | "終"
  | "絵"
  | "網"
  | "綿"
  | "縦"
  | "織"
  | "纂"
  | "羅"
  | "羊"
  | "美"
  | "羚"
  | "翰"
  | "而"
  | "耒"
  | "耳"
  | "聚"
  | "聯"
  | "肉"
  | "育"
  | "背"
  | "胸"
  | "能"
  | "脂"
  | "腹"
  | "膠"
  | "船"
  | "色"
  | "花"
  | "茶"
  | "草"
  | "菓"
  | "虎"
  | "虫"
  | "蛋"
  | "蜜"
  | "血"
  | "行"
  | "術"
  | "衣"
  | "裁"
  | "西"
  | "覆"
  | "言"
  | "認"
  | "論"
  | "謝"
  | "識"
  | "谷"
  | "豆"
  | "豊"
  | "貓"
  | "貝"
  | "貧"
  | "質"
  | "赤"
  | "足"
  | "躍"
  | "車"
  | "軍"
  | "軟"
  | "軸"
  | "軽"
  | "輝"
  | "輩"
  | "輪"
  | "近"
  | "迷"
  | "通"
  | "連"
  | "遊"
  | "道"
  | "遠"
  | "酒"
  | "醇"
  | "金"
  | "針"
  | "銭"
  | "錘"
  | "鎖"
  | "鑓"
  | "長"
  | "門"
  | "閉"
  | "開"
  | "閥"
  | "闇"
  | "陸"
  | "隊"
  | "集"
  | "雪"
  | "震"
  | "青"
  | "静"
  | "須"
  | "頬"
  | "頭"
  | "顔"
  | "類"
  | "顫"
  | "風"
  | "馬"
  | "骨"
  | "高"
  | "魚"
  | "鳥"
  | "鶏"
  | "麗"
  | "黒"
  | "墨"
  | "鼓"
  | "龍";

export type GeometricLinzklarKey =
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | "";

export enum GeometricLinzklar {
   = "一",
   = "七",
   = "三",
   = "上",
   = "下",
   = "与",
   = "中",
   = "之",
   = "乎",
   = "九",
   = "二",
   = "互",
   = "五",
   = "亦",
   = "享",
   = "人",
   = "从",
   = "付",
   = "件",
   = "位",
   = "低",
   = "体",
   = "何",
   = "佰",
   = "使",
   = "俐",
   = "倉",
   = "倒",
   = "値",
   = "健",
   = "傷",
   = "傾",
   = "僚",
   = "兄",
   = "光",
   = "党",
   = "入",
   = "全",
   = "八",
   = "六",
   = "兵",
   = "其",
   = "内",
   = "再",
   = "冠",
   = "冬",
   = "処",
   = "凹",
   = "函",
   = "刀",
   = "別",
   = "刺",
   = "刻",
   = "前",
   = "力",
   = "加",
   = "助",
   = "労",
   = "勿",
   = "包",
   = "北",
   = "十",
   = "南",
   = "即",
   = "卵",
   = "友",
   = "反",
   = "受",
   = "叛",
   = "口",
   = "古",
   = "叫",
   = "可",
   = "右",
   = "吁",
   = "同",
   = "名",
   = "后",
   = "吏",
   = "㕮",
   = "周",
   = "味",
   = "呻",
   = "咍",
   = "哇",
   = "哩",
   = "唯",
   = "啌",
   = "善",
   = "嗅",
   = "噫",
   = "囁",
   = "四",
   = "囲",
   = "国",
   = "圧",
   = "在",
   = "地",
   = "型",
   = "増",
   = "壁",
   = "壊",
   = "声",
   = "夏",
   = "外",
   = "夘",
   = "多",
   = "大",
   = "天",
   = "失",
   = "奮",
   = "女",
   = "如",
   = "始",
   = "子",
   = "字",
   = "季",
   = "学",
   = "守",
   = "官",
   = "定",
   = "宦",
   = "家",
   = "寐",
   = "寒",
   = "寝",
   = "将",
   = "小",
   = "少",
   = "属",
   = "層",
   = "山",
   = "岩",
   = "島",
   = "川",
   = "左",
   = "巫",
   = "己",
   = "巻",
   = "布",
   = "帝",
   = "席",
   = "常",
   = "帽",
   = "平",
   = "広",
   = "店",
   = "座",
   = "弓",
   = "形",
   = "彼",
   = "律",
   = "後",
   = "従",
   = "御",
   = "心",
   = "必",
   = "怖",
   = "思",
   = "急",
   = "恒",
   = "悪",
   = "意",
   = "我",
   = "或",
   = "戦",
   = "手",
   = "抗",
   = "振",
   = "挽",
   = "撃",
   = "故",
   = "救",
   = "散",
   = "文",
   = "斧",
   = "新",
   = "於",
   = "族",
   = "日",
   = "星",
   = "春",
   = "時",
   = "普",
   = "書",
   = "月",
   = "木",
   = "机",
   = "村",
   = "来",
   = "杯",
   = "東",
   = "果",
   = "柔",
   = "株",
   = "械",
   = "棉",
   = "棚",
   = "極",
   = "榎",
   = "槍",
   = "横",
   = "樽",
   = "橋",
   = "機",
   = "欽",
   = "歌",
   = "止",
   = "正",
   = "此",
   = "歪",
   = "母",
   = "毎",
   = "毛",
   = "氏",
   = "民",
   = "水",
   = "汝",
   = "汪",
   = "決",
   = "油",
   = "浬",
   = "海",
   = "淮",
   = "深",
   = "混",
   = "清",
   = "満",
   = "激",
   = "火",
   = "為",
   = "無",
   = "煙",
   = "父",
   = "片",
   = "牌",
   = "牛",
   = "牡",
   = "物",
   = "犬",
   = "猫",
   = "獣",
   = "王",
   = "球",
   = "琴",
   = "瑪",
   = "甘",
   = "生",
   = "産",
   = "男",
   = "疲",
   = "白",
   = "百",
   = "皇",
   = "皷",
   = "目",
   = "直",
   = "真",
   = "短",
   = "石",
   = "硫",
   = "硬",
   = "祖",
   = "神",
   = "祭",
   = "禦",
   = "秋",
   = "科",
   = "種",
   = "積",
   = "穏",
   = "穐",
   = "穴",
   = "立",
   = "端",
   = "竹",
   = "竺",
   = "笑",
   = "笙",
   = "笛",
   = "筆",
   = "等",
   = "筒",
   = "箏",
   = "箱",
   = "米",
   = "糸",
   = "紙",
   = "素",
   = "累",
   = "終",
   = "絵",
   = "網",
   = "綿",
   = "縦",
   = "織",
   = "纂",
   = "羅",
   = "羊",
   = "美",
   = "羚",
   = "翰",
   = "而",
   = "耒",
   = "耳",
   = "聚",
   = "聯",
   = "肉",
   = "育",
   = "背",
   = "胸",
   = "能",
   = "脂",
   = "腹",
   = "膠",
   = "船",
   = "色",
   = "花",
   = "茶",
   = "草",
   = "菓",
   = "虎",
   = "虫",
   = "蛋",
   = "蜜",
   = "血",
   = "行",
   = "術",
   = "衣",
   = "裁",
   = "西",
   = "覆",
   = "言",
   = "認",
   = "論",
   = "謝",
   = "識",
   = "谷",
   = "豆",
   = "豊",
   = "貓",
   = "貝",
   = "貧",
   = "質",
   = "赤",
   = "足",
   = "躍",
   = "車",
   = "軍",
   = "軟",
   = "軸",
   = "軽",
   = "輝",
   = "輩",
   = "輪",
   = "近",
   = "迷",
   = "通",
   = "連",
   = "遊",
   = "道",
   = "遠",
   = "酒",
   = "醇",
   = "金",
   = "針",
   = "銭",
   = "錘",
   = "鎖",
   = "鑓",
   = "長",
   = "門",
   = "閉",
   = "開",
   = "閥",
   = "闇",
   = "陸",
   = "隊",
   = "集",
   = "雪",
   = "震",
   = "青",
   = "静",
   = "須",
   = "頬",
   = "頭",
   = "顔",
   = "類",
   = "顫",
   = "風",
   = "馬",
   = "骨",
   = "高",
   = "魚",
   = "鳥",
   = "鶏",
   = "麗",
   = "黒",
   = "墨",
   = "鼓",
   = "龍",
}

export const GEOMETRIC_LINZKLAR_CODEPOINTS: { [key in GeometricLinzklar]: string } = {
  [GeometricLinzklar.]: "19968",
  [GeometricLinzklar.]: "19971",
  [GeometricLinzklar.]: "19977",
  [GeometricLinzklar.]: "19978",
  [GeometricLinzklar.]: "19979",
  [GeometricLinzklar.]: "19982",
  [GeometricLinzklar.]: "20013",
  [GeometricLinzklar.]: "20043",
  [GeometricLinzklar.]: "20046",
  [GeometricLinzklar.]: "20061",
  [GeometricLinzklar.]: "20108",
  [GeometricLinzklar.]: "20114",
  [GeometricLinzklar.]: "20116",
  [GeometricLinzklar.]: "20134",
  [GeometricLinzklar.]: "20139",
  [GeometricLinzklar.]: "20154",
  [GeometricLinzklar.]: "20174",
  [GeometricLinzklar.]: "20184",
  [GeometricLinzklar.]: "20214",
  [GeometricLinzklar.]: "20301",
  [GeometricLinzklar.]: "20302",
  [GeometricLinzklar.]: "20307",
  [GeometricLinzklar.]: "20309",
  [GeometricLinzklar.]: "20336",
  [GeometricLinzklar.]: "20351",
  [GeometricLinzklar.]: "20432",
  [GeometricLinzklar.]: "20489",
  [GeometricLinzklar.]: "20498",
  [GeometricLinzklar.]: "20516",
  [GeometricLinzklar.]: "20581",
  [GeometricLinzklar.]: "20663",
  [GeometricLinzklar.]: "20670",
  [GeometricLinzklar.]: "20698",
  [GeometricLinzklar.]: "20804",
  [GeometricLinzklar.]: "20809",
  [GeometricLinzklar.]: "20826",
  [GeometricLinzklar.]: "20837",
  [GeometricLinzklar.]: "20840",
  [GeometricLinzklar.]: "20843",
  [GeometricLinzklar.]: "20845",
  [GeometricLinzklar.]: "20853",
  [GeometricLinzklar.]: "20854",
  [GeometricLinzklar.]: "20869",
  [GeometricLinzklar.]: "20877",
  [GeometricLinzklar.]: "20896",
  [GeometricLinzklar.]: "20908",
  [GeometricLinzklar.]: "20966",
  [GeometricLinzklar.]: "20985",
  [GeometricLinzklar.]: "20989",
  [GeometricLinzklar.]: "20992",
  [GeometricLinzklar.]: "21029",
  [GeometricLinzklar.]: "21050",
  [GeometricLinzklar.]: "21051",
  [GeometricLinzklar.]: "21069",
  [GeometricLinzklar.]: "21147",
  [GeometricLinzklar.]: "21152",
  [GeometricLinzklar.]: "21161",
  [GeometricLinzklar.]: "21172",
  [GeometricLinzklar.]: "21247",
  [GeometricLinzklar.]: "21253",
  [GeometricLinzklar.]: "21271",
  [GeometricLinzklar.]: "21313",
  [GeometricLinzklar.]: "21335",
  [GeometricLinzklar.]: "21363",
  [GeometricLinzklar.]: "21365",
  [GeometricLinzklar.]: "21451",
  [GeometricLinzklar.]: "21453",
  [GeometricLinzklar.]: "21463",
  [GeometricLinzklar.]: "21467",
  [GeometricLinzklar.]: "21475",
  [GeometricLinzklar.]: "21476",
  [GeometricLinzklar.]: "21483",
  [GeometricLinzklar.]: "21487",
  [GeometricLinzklar.]: "21491",
  [GeometricLinzklar.]: "21505",
  [GeometricLinzklar.]: "21516",
  [GeometricLinzklar.]: "21517",
  [GeometricLinzklar.]: "21518",
  [GeometricLinzklar.]: "21519",
  [GeometricLinzklar.]: "13678",
  [GeometricLinzklar.]: "21608",
  [GeometricLinzklar.]: "21619",
  [GeometricLinzklar.]: "21627",
  [GeometricLinzklar.]: "21645",
  [GeometricLinzklar.]: "21703",
  [GeometricLinzklar.]: "21737",
  [GeometricLinzklar.]: "21807",
  [GeometricLinzklar.]: "21836",
  [GeometricLinzklar.]: "21892",
  [GeometricLinzklar.]: "21957",
  [GeometricLinzklar.]: "22123",
  [GeometricLinzklar.]: "22209",
  [GeometricLinzklar.]: "22235",
  [GeometricLinzklar.]: "22258",
  [GeometricLinzklar.]: "22269",
  [GeometricLinzklar.]: "22311",
  [GeometricLinzklar.]: "22312",
  [GeometricLinzklar.]: "22320",
  [GeometricLinzklar.]: "22411",
  [GeometricLinzklar.]: "22679",
  [GeometricLinzklar.]: "22721",
  [GeometricLinzklar.]: "22730",
  [GeometricLinzklar.]: "22768",
  [GeometricLinzklar.]: "22799",
  [GeometricLinzklar.]: "22806",
  [GeometricLinzklar.]: "22808",
  [GeometricLinzklar.]: "22810",
  [GeometricLinzklar.]: "22823",
  [GeometricLinzklar.]: "22825",
  [GeometricLinzklar.]: "22833",
  [GeometricLinzklar.]: "22894",
  [GeometricLinzklar.]: "22899",
  [GeometricLinzklar.]: "22914",
  [GeometricLinzklar.]: "22987",
  [GeometricLinzklar.]: "23376",
  [GeometricLinzklar.]: "23383",
  [GeometricLinzklar.]: "23395",
  [GeometricLinzklar.]: "23398",
  [GeometricLinzklar.]: "23432",
  [GeometricLinzklar.]: "23448",
  [GeometricLinzklar.]: "23450",
  [GeometricLinzklar.]: "23462",
  [GeometricLinzklar.]: "23478",
  [GeometricLinzklar.]: "23504",
  [GeometricLinzklar.]: "23506",
  [GeometricLinzklar.]: "23517",
  [GeometricLinzklar.]: "23558",
  [GeometricLinzklar.]: "23567",
  [GeometricLinzklar.]: "23569",
  [GeometricLinzklar.]: "23646",
  [GeometricLinzklar.]: "23652",
  [GeometricLinzklar.]: "23665",
  [GeometricLinzklar.]: "23721",
  [GeometricLinzklar.]: "23798",
  [GeometricLinzklar.]: "24029",
  [GeometricLinzklar.]: "24038",
  [GeometricLinzklar.]: "24043",
  [GeometricLinzklar.]: "24049",
  [GeometricLinzklar.]: "24059",
  [GeometricLinzklar.]: "24067",
  [GeometricLinzklar.]: "24093",
  [GeometricLinzklar.]: "24109",
  [GeometricLinzklar.]: "24120",
  [GeometricLinzklar.]: "24125",
  [GeometricLinzklar.]: "24179",
  [GeometricLinzklar.]: "24195",
  [GeometricLinzklar.]: "24215",
  [GeometricLinzklar.]: "24231",
  [GeometricLinzklar.]: "24339",
  [GeometricLinzklar.]: "24418",
  [GeometricLinzklar.]: "24444",
  [GeometricLinzklar.]: "24459",
  [GeometricLinzklar.]: "24460",
  [GeometricLinzklar.]: "24467",
  [GeometricLinzklar.]: "24481",
  [GeometricLinzklar.]: "24515",
  [GeometricLinzklar.]: "24517",
  [GeometricLinzklar.]: "24598",
  [GeometricLinzklar.]: "24605",
  [GeometricLinzklar.]: "24613",
  [GeometricLinzklar.]: "24658",
  [GeometricLinzklar.]: "24746",
  [GeometricLinzklar.]: "24847",
  [GeometricLinzklar.]: "25105",
  [GeometricLinzklar.]: "25110",
  [GeometricLinzklar.]: "25126",
  [GeometricLinzklar.]: "25163",
  [GeometricLinzklar.]: "25239",
  [GeometricLinzklar.]: "25391",
  [GeometricLinzklar.]: "25405",
  [GeometricLinzklar.]: "25731",
  [GeometricLinzklar.]: "25925",
  [GeometricLinzklar.]: "25937",
  [GeometricLinzklar.]: "25955",
  [GeometricLinzklar.]: "25991",
  [GeometricLinzklar.]: "26023",
  [GeometricLinzklar.]: "26032",
  [GeometricLinzklar.]: "26044",
  [GeometricLinzklar.]: "26063",
  [GeometricLinzklar.]: "26085",
  [GeometricLinzklar.]: "26143",
  [GeometricLinzklar.]: "26149",
  [GeometricLinzklar.]: "26178",
  [GeometricLinzklar.]: "26222",
  [GeometricLinzklar.]: "26360",
  [GeometricLinzklar.]: "26376",
  [GeometricLinzklar.]: "26408",
  [GeometricLinzklar.]: "26426",
  [GeometricLinzklar.]: "26449",
  [GeometricLinzklar.]: "26469",
  [GeometricLinzklar.]: "26479",
  [GeometricLinzklar.]: "26481",
  [GeometricLinzklar.]: "26524",
  [GeometricLinzklar.]: "26580",
  [GeometricLinzklar.]: "26666",
  [GeometricLinzklar.]: "26800",
  [GeometricLinzklar.]: "26825",
  [GeometricLinzklar.]: "26842",
  [GeometricLinzklar.]: "26997",
  [GeometricLinzklar.]: "27022",
  [GeometricLinzklar.]: "27085",
  [GeometricLinzklar.]: "27178",
  [GeometricLinzklar.]: "27197",
  [GeometricLinzklar.]: "27211",
  [GeometricLinzklar.]: "27231",
  [GeometricLinzklar.]: "27453",
  [GeometricLinzklar.]: "27468",
  [GeometricLinzklar.]: "27490",
  [GeometricLinzklar.]: "27491",
  [GeometricLinzklar.]: "27492",
  [GeometricLinzklar.]: "27498",
  [GeometricLinzklar.]: "27597",
  [GeometricLinzklar.]: "27598",
  [GeometricLinzklar.]: "27611",
  [GeometricLinzklar.]: "27663",
  [GeometricLinzklar.]: "27665",
  [GeometricLinzklar.]: "27700",
  [GeometricLinzklar.]: "27741",
  [GeometricLinzklar.]: "27754",
  [GeometricLinzklar.]: "27770",
  [GeometricLinzklar.]: "27833",
  [GeometricLinzklar.]: "28012",
  [GeometricLinzklar.]: "28023",
  [GeometricLinzklar.]: "28142",
  [GeometricLinzklar.]: "28145",
  [GeometricLinzklar.]: "28151",
  [GeometricLinzklar.]: "28165",
  [GeometricLinzklar.]: "28288",
  [GeometricLinzklar.]: "28608",
  [GeometricLinzklar.]: "28779",
  [GeometricLinzklar.]: "28858",
  [GeometricLinzklar.]: "28961",
  [GeometricLinzklar.]: "29017",
  [GeometricLinzklar.]: "29238",
  [GeometricLinzklar.]: "29255",
  [GeometricLinzklar.]: "29260",
  [GeometricLinzklar.]: "29275",
  [GeometricLinzklar.]: "29281",
  [GeometricLinzklar.]: "29289",
  [GeometricLinzklar.]: "29356",
  [GeometricLinzklar.]: "29483",
  [GeometricLinzklar.]: "29539",
  [GeometricLinzklar.]: "29579",
  [GeometricLinzklar.]: "29699",
  [GeometricLinzklar.]: "29748",
  [GeometricLinzklar.]: "29802",
  [GeometricLinzklar.]: "29976",
  [GeometricLinzklar.]: "29983",
  [GeometricLinzklar.]: "29987",
  [GeometricLinzklar.]: "30007",
  [GeometricLinzklar.]: "30130",
  [GeometricLinzklar.]: "30333",
  [GeometricLinzklar.]: "30334",
  [GeometricLinzklar.]: "30343",
  [GeometricLinzklar.]: "30391",
  [GeometricLinzklar.]: "30446",
  [GeometricLinzklar.]: "30452",
  [GeometricLinzklar.]: "30495",
  [GeometricLinzklar.]: "30701",
  [GeometricLinzklar.]: "30707",
  [GeometricLinzklar.]: "30827",
  [GeometricLinzklar.]: "30828",
  [GeometricLinzklar.]: "31062",
  [GeometricLinzklar.]: "31070",
  [GeometricLinzklar.]: "31085",
  [GeometricLinzklar.]: "31142",
  [GeometricLinzklar.]: "31179",
  [GeometricLinzklar.]: "31185",
  [GeometricLinzklar.]: "31278",
  [GeometricLinzklar.]: "31309",
  [GeometricLinzklar.]: "31311",
  [GeometricLinzklar.]: "31312",
  [GeometricLinzklar.]: "31348",
  [GeometricLinzklar.]: "31435",
  [GeometricLinzklar.]: "31471",
  [GeometricLinzklar.]: "31481",
  [GeometricLinzklar.]: "31482",
  [GeometricLinzklar.]: "31505",
  [GeometricLinzklar.]: "31513",
  [GeometricLinzklar.]: "31515",
  [GeometricLinzklar.]: "31558",
  [GeometricLinzklar.]: "31561",
  [GeometricLinzklar.]: "31570",
  [GeometricLinzklar.]: "31631",
  [GeometricLinzklar.]: "31665",
  [GeometricLinzklar.]: "31859",
  [GeometricLinzklar.]: "31992",
  [GeometricLinzklar.]: "32025",
  [GeometricLinzklar.]: "32032",
  [GeometricLinzklar.]: "32047",
  [GeometricLinzklar.]: "32066",
  [GeometricLinzklar.]: "32117",
  [GeometricLinzklar.]: "32178",
  [GeometricLinzklar.]: "32191",
  [GeometricLinzklar.]: "32294",
  [GeometricLinzklar.]: "32340",
  [GeometricLinzklar.]: "32386",
  [GeometricLinzklar.]: "32645",
  [GeometricLinzklar.]: "32650",
  [GeometricLinzklar.]: "32654",
  [GeometricLinzklar.]: "32666",
  [GeometricLinzklar.]: "32752",
  [GeometricLinzklar.]: "32780",
  [GeometricLinzklar.]: "32786",
  [GeometricLinzklar.]: "32819",
  [GeometricLinzklar.]: "32858",
  [GeometricLinzklar.]: "32879",
  [GeometricLinzklar.]: "32905",
  [GeometricLinzklar.]: "32946",
  [GeometricLinzklar.]: "32972",
  [GeometricLinzklar.]: "33016",
  [GeometricLinzklar.]: "33021",
  [GeometricLinzklar.]: "33026",
  [GeometricLinzklar.]: "33145",
  [GeometricLinzklar.]: "33184",
  [GeometricLinzklar.]: "33337",
  [GeometricLinzklar.]: "33394",
  [GeometricLinzklar.]: "33457",
  [GeometricLinzklar.]: "33590",
  [GeometricLinzklar.]: "33609",
  [GeometricLinzklar.]: "33747",
  [GeometricLinzklar.]: "34382",
  [GeometricLinzklar.]: "34411",
  [GeometricLinzklar.]: "34507",
  [GeometricLinzklar.]: "34588",
  [GeometricLinzklar.]: "34880",
  [GeometricLinzklar.]: "34892",
  [GeometricLinzklar.]: "34899",
  [GeometricLinzklar.]: "34915",
  [GeometricLinzklar.]: "35009",
  [GeometricLinzklar.]: "35199",
  [GeometricLinzklar.]: "35206",
  [GeometricLinzklar.]: "35328",
  [GeometricLinzklar.]: "35469",
  [GeometricLinzklar.]: "35542",
  [GeometricLinzklar.]: "35613",
  [GeometricLinzklar.]: "35672",
  [GeometricLinzklar.]: "35895",
  [GeometricLinzklar.]: "35910",
  [GeometricLinzklar.]: "35914",
  [GeometricLinzklar.]: "35987",
  [GeometricLinzklar.]: "35997",
  [GeometricLinzklar.]: "36007",
  [GeometricLinzklar.]: "36074",
  [GeometricLinzklar.]: "36196",
  [GeometricLinzklar.]: "36275",
  [GeometricLinzklar.]: "36493",
  [GeometricLinzklar.]: "36554",
  [GeometricLinzklar.]: "36557",
  [GeometricLinzklar.]: "36575",
  [GeometricLinzklar.]: "36600",
  [GeometricLinzklar.]: "36605",
  [GeometricLinzklar.]: "36637",
  [GeometricLinzklar.]: "36649",
  [GeometricLinzklar.]: "36650",
  [GeometricLinzklar.]: "36817",
  [GeometricLinzklar.]: "36855",
  [GeometricLinzklar.]: "36890",
  [GeometricLinzklar.]: "36899",
  [GeometricLinzklar.]: "36938",
  [GeometricLinzklar.]: "36947",
  [GeometricLinzklar.]: "36960",
  [GeometricLinzklar.]: "37202",
  [GeometricLinzklar.]: "37255",
  [GeometricLinzklar.]: "37329",
  [GeometricLinzklar.]: "37341",
  [GeometricLinzklar.]: "37549",
  [GeometricLinzklar.]: "37656",
  [GeometricLinzklar.]: "37782",
  [GeometricLinzklar.]: "37971",
  [GeometricLinzklar.]: "38263",
  [GeometricLinzklar.]: "38272",
  [GeometricLinzklar.]: "38281",
  [GeometricLinzklar.]: "38283",
  [GeometricLinzklar.]: "38309",
  [GeometricLinzklar.]: "38343",
  [GeometricLinzklar.]: "38520",
  [GeometricLinzklar.]: "38538",
  [GeometricLinzklar.]: "38598",
  [GeometricLinzklar.]: "38634",
  [GeometricLinzklar.]: "38663",
  [GeometricLinzklar.]: "38738",
  [GeometricLinzklar.]: "38745",
  [GeometricLinzklar.]: "38920",
  [GeometricLinzklar.]: "38956",
  [GeometricLinzklar.]: "38957",
  [GeometricLinzklar.]: "38996",
  [GeometricLinzklar.]: "39006",
  [GeometricLinzklar.]: "39019",
  [GeometricLinzklar.]: "39080",
  [GeometricLinzklar.]: "39340",
  [GeometricLinzklar.]: "39592",
  [GeometricLinzklar.]: "39640",
  [GeometricLinzklar.]: "39770",
  [GeometricLinzklar.]: "40165",
  [GeometricLinzklar.]: "40335",
  [GeometricLinzklar.]: "40599",
  [GeometricLinzklar.]: "40658",
  [GeometricLinzklar.]: "22696",
  [GeometricLinzklar.]: "40723",
  [GeometricLinzklar.]: "40845",
};
